# Generated by Django 5.0.1 on 2025-02-03 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="content",
            name="file",
        ),
        migrations.RemoveField(
            model_name="content",
            name="updated_at",
        ),
    ]
